### ISSUE TITLE
Errors when trying to compile code on Raspberry Pi 3 Model 3B+

### ISSUE THREAD

**Issue by PRASANNA-RAVI** [neon-ntt/neon-ntt#1]
Hello,
   I am trying to compile the project on Rpi 3 Model B+. I tried to compile the makefile in the microbenchmaks folder of several schemes. But, I am getting a large number of errors. Mainly stating that the assembly instructions used are bad instructions... 
For example,
(1)  __asm_NTT.S:13: Error: bad instruction 'stp x19,x20,[sp,#16*0]'.
(2) unknown register 'x0' -- .req ignored

Apologies for my naivety, as I am new to NEON implementation. Is there any change that needs to be done to make the project work on Rpi 3 Model B+.

With Thanks and Regards,
Prasanna Ravi.

**Comment by PRASANNA-RAVI** [comment]
[errors.txt](https://github.com/neon-ntt/neon-ntt/files/7560680/errors.txt)

I have also attached the error log, when trying to compile kyber512. Thanks...

**Comment by vincentvbh** [comment]
Hi PRASANNA-RAVI, can you provide the information about the compiler?

Vincent

**Comment by PRASANNA-RAVI** [comment]
Thanks for the prompt Response, Vincent.

The compiler is 

gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516

Regards,
Prasanna Ravi

**Comment by PRASANNA-RAVI** [comment]
Hi Vincent, 

Just to let you know, I tried to run the pqax benchmarks, but they run fine without any issues. I believe that code is also meant for aarch64. However, I think the implementation is based on Neon Intrinsics, but I guess the neon-ntt is based on pure ARM assembly. Please correct me if I am wrong.

With Thanks and Regards,
Prasanna Ravi.

**Comment by PRASANNA-RAVI** [comment]
Hi Vincent,
 I also tried to compile with an upgraded version of gcc - (Debian 11.2.0-10) 11.2.0. But, I receive almost identical errors.

With Thanks and Regards,
Prasanna Ravi.

**Comment by vincentvbh** [comment]
Hi PRASANNA-RAVI,

Indeed, the code in pqax is based on Neon Intrinsics and it seems that your compiler is not able to recognize our assembly code. I haven't compiled with Raspbian so it might take some time to figure out what's going on. 

To be specific, we compiled our code with GCC 10 that can be acquired for ubuntu 21.04.

Vincent

**Comment by PRASANNA-RAVI** [comment]
Dear Vincent,
       Thank you for your response. I will keep you updated if I am able to correct the errors. Thanks again for your co-operation.

Regards,
Prasanna Ravi.

**Comment by mkannwischer** [comment]
Hi @PRASANNA-RAVI, 

can you let us know what `uname -a` gives you?

Cheers, 
Matthias

**Comment by PRASANNA-RAVI** [comment]
Hi Matthias,
       Thanks for your response. 

For uname -a, we get 

Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by mkannwischer** [comment]
That looks like a 32-bit kernel. You will need to install a 64-bit OS to use our code. 
For example, http://downloads.raspberrypi.org/raspios_arm64/images/. 

We used Ubuntu instead, but I am not sure how well that will run on the RPi3. 

Let me know if that works for you.

**Comment by PRASANNA-RAVI** [comment]
Thanks for the response, Matthias. But, isnt pqax code meant for aarch64 as well ? I am able to run the pqax code for kyber and saber. Apologies, if there anything that I am missing...

With Thanks and Regards,
Prasanna Ravi.

**Comment by vincentvbh** [comment]
There are folders for different architectures. Programs under the name aarch64 will only be built when running on a 64-bit OS.

Vincent

**Comment by mkannwischer** [comment]
pqax works on both `aarch64` and `aarch32`. 
On `aarch32`, the `aarch64` implementations will be ignored. This should be the case for the implementations with the intrinsics. 
I'm suspecting that what you have been running was the `clean` implementation from PQClean compiled for `aarch32`. 

If I am right, the elf should be called `mupq_pqclean_crypto_kem_kyber768_clean_test.elf` rather than `crypto_kem_kyber768_aarch64_test.elf`.

**Comment by PRASANNA-RAVI** [comment]
Dear Matthias,
                       You are right. I have verified that pqax was originally running on the aarch32 OS and only generated  mupq_pqclean_crypto_kem_kyber768_clean_test.elf, and not the aarch64 one. I also managed to burn the aarch64 OS and I can verify that the neon-ntt implementation of kyber768 works fine on that one. No errors there.

Thank you very much for patiently helping me resolve the issue. Also, Thanks to Vincent for the quick response. Appeciate it!!

Thanks,
Prasanna Ravi.
