### ISSUE TITLE
Dual licensing

### ISSUE THREAD

**Issue by dstebila** [neon-ntt/neon-ntt#3]
In liboqs we've gotten some feedback (https://github.com/open-quantum-safe/liboqs/issues/1437) that the CC0 license is a barrier to adoption by some distributions. Would you be willing to consider dual licensing this code to add another license? See also https://github.com/open-quantum-safe/liboqs/issues/1388#issuecomment-1430046692 for comments from the Fedora team.

**Comment by vincentvbh** [comment]
Hi, @dstebila. 

I'm okay with MIT and will discuss the dual licensing with other co-authors. 
Does adding MIT solve the issues?

Thanks,
Vincent

**Comment by dstebila** [comment]
> I'm okay with MIT and will discuss the dual licensing with other co-authors. 
> 
> Does adding MIT solve the issues?

Yes, MIT should be fine.

**Comment by dstebila** [comment]
Hi @vincentvbh, any feedback from the other authors on making this MIT licensed?

**Comment by vincentvbh** [comment]
Hi @dstebila,

Yes, everyone agrees with MIT.
Currently, Dilithium is basically done.
I'm still adding the license for Kyber.

**Comment by dstebila** [comment]
Great! Thanks for the update.

**Comment by hanno-becker** [comment]
@dstebila FYI some of us recently improved the Neon NTT further in https://eprint.iacr.org/2022/1303, the code for which is available under MIT on https://github.com/slothy-optimizer/slothy and https://github.com/slothy-optimizer/pqax.
