### ISSUE TITLE
Dilithium does not build on M1 Mac

### ISSUE THREAD

**Issue by gaatorre** [neon-ntt/neon-ntt#5]
Hello,

Building any of the Dilithium versions on a M1 Mac fails. It errors out because `TRBYTES`, `CTILDEBYTES`, and `RNDBYTES` are undefined.

Here is the full log of building Dilithium2.
[errors.txt](https://github.com/neon-ntt/neon-ntt/files/13208229/errors.txt)

**Comment by vincentvbh** [comment]
Thanks for the report. I'll try to fix it this week.

**Comment by vincentvbh** [comment]
This should be fixed with the new commit

443d5c416c7719098988918c7695290c208fc319

@gaatorre can you double-check this?

Thanks

**Comment by gaatorre** [comment]
Builds and tests pass for all three security levels.

Thanks for getting to this!
